# Generated by Django 5.0.7 on 2024-08-13 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_category_event_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='publish',
        ),
    ]
